GET http://localhost:3000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWGltZW5lcyIsImlhdCI6MTYxMjgzMjIzNiwiZXhwIjoxNjEyODMyMjY2fQ.fMRj4Ilp-acPERnX5DlDNSMl9xcHPNOBGKSjjUdTPpc


###

POST http://localhost:4000/login
Content-Type: application/json

{
    "name": "Ximenes",
    "password": "******"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWGltZW5lcyIsImlhdCI6MTYxMjgzMjM4OX0.-aHq2HuBkEjdRGisx48EVpL7eLLhrR61EVOc6fzyfSA"
}


###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWGltZW5lcyIsImlhdCI6MTYxMjczMzA3Mn0.NqidmqyJ9APumi5Pm1Bk60oYLGykSPqwwZiojCmwRUE"

}